// <auto-generated />
using System;
using DietApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietApp.DAL.Migrations
{
    [DbContext(typeof(DietAppDBContext))]
<<<<<<<< HEAD:DietApp/DietApp.DAL/Migrations/20240209195155_initial.Designer.cs
    [Migration("20240209195155_initial")]
    partial class initial
========
    [Migration("20240209200521_a")]
    partial class a
>>>>>>>> origin/asd:DietApp/DietApp.DAL/Migrations/20240209200521_a.Designer.cs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DietApp.Entities.GunlukRapor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<double>("Kalori")
                        .HasColumnType("float");

                    b.Property<double>("KarbonhidratMiktari")
                        .HasColumnType("float");

                    b.Property<int?>("KullaniciKisiselID")
                        .HasColumnType("int");

                    b.Property<double>("ProteinMiktari")
                        .HasColumnType("float");

                    b.Property<DateTime>("SecilenRaporTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SuMiktari")
                        .HasColumnType("int");

                    b.Property<double>("YagMiktari")
                        .HasColumnType("float");

                    b.Property<string>("YemekAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciKisiselID");

                    b.ToTable("GunlukRapor");
                });

            modelBuilder.Entity("DietApp.Entities.Kategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kategori");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            KategoriAdi = "Meyve"
                        });
                });

            modelBuilder.Entity("DietApp.Entities.KullaniciGiris", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciKisiselID")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KullaniciGiris");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            KullaniciAdi = "YalinTuzmen",
                            KullaniciKisiselID = 1,
                            Sifre = "A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3"
                        },
                        new
                        {
                            ID = 2,
                            KullaniciAdi = "SilaYildirim",
                            KullaniciKisiselID = 2,
                            Sifre = "A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3"
                        },
                        new
                        {
                            ID = 3,
                            KullaniciAdi = "DamlaGurel",
                            KullaniciKisiselID = 3,
                            Sifre = "A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3"
                        },
                        new
                        {
                            ID = 4,
                            KullaniciAdi = "admin",
                            KullaniciKisiselID = 4,
                            Sifre = "8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918"
                        },
                        new
                        {
                            ID = 5,
                            KullaniciAdi = "a",
                            KullaniciKisiselID = 5,
                            Sifre = "CA978112CA1BBDCAFAC231B39A23DC4DA786EFF8147C4E72B9807785AFEE48BB"
                        });
                });

            modelBuilder.Entity("DietApp.Entities.KullaniciKisisel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("Boy")
                        .HasColumnType("float");

                    b.Property<bool>("Cinsiyet")
                        .HasColumnType("bit");

                    b.Property<double>("GunlukKalori")
                        .HasColumnType("float");

                    b.Property<double>("HedefKilo")
                        .HasColumnType("float");

                    b.Property<double>("HedefSuMiktari")
                        .HasColumnType("float");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kilo")
                        .HasColumnType("float");

                    b.Property<int>("KullaniciGirisID")
                        .HasColumnType("int");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciGirisID")
                        .IsUnique();

                    b.ToTable("KullaniciKisisel");

                    b.HasData(
                        new
                        {
                            ID = 1,
<<<<<<<< HEAD:DietApp/DietApp.DAL/Migrations/20240209195155_initial.Designer.cs
                            BaslangicTarihi = new DateTime(2024, 2, 9, 22, 51, 54, 727, DateTimeKind.Local).AddTicks(7283),
========
                            BaslangicTarihi = new DateTime(2024, 2, 9, 23, 5, 21, 721, DateTimeKind.Local).AddTicks(9540),
>>>>>>>> origin/asd:DietApp/DietApp.DAL/Migrations/20240209200521_a.Designer.cs
                            BitisTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Boy = 170.0,
                            Cinsiyet = false,
                            GunlukKalori = 3000.0,
                            HedefKilo = 70.0,
                            HedefSuMiktari = 2000.0,
                            Isim = "ahmet",
                            Kilo = 80.0,
                            KullaniciGirisID = 1,
                            Soyisim = "mehmet",
                            Yas = 18
                        },
                        new
                        {
                            ID = 2,
<<<<<<<< HEAD:DietApp/DietApp.DAL/Migrations/20240209195155_initial.Designer.cs
                            BaslangicTarihi = new DateTime(2024, 2, 9, 22, 51, 54, 727, DateTimeKind.Local).AddTicks(7301),
========
                            BaslangicTarihi = new DateTime(2024, 2, 9, 23, 5, 21, 721, DateTimeKind.Local).AddTicks(9548),
>>>>>>>> origin/asd:DietApp/DietApp.DAL/Migrations/20240209200521_a.Designer.cs
                            BitisTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Boy = 170.0,
                            Cinsiyet = false,
                            GunlukKalori = 3000.0,
                            HedefKilo = 70.0,
                            HedefSuMiktari = 2000.0,
                            Isim = "ahmet",
                            Kilo = 80.0,
                            KullaniciGirisID = 2,
                            Soyisim = "mehmet",
                            Yas = 18
                        },
                        new
                        {
                            ID = 3,
<<<<<<<< HEAD:DietApp/DietApp.DAL/Migrations/20240209195155_initial.Designer.cs
                            BaslangicTarihi = new DateTime(2024, 2, 9, 22, 51, 54, 727, DateTimeKind.Local).AddTicks(7304),
========
                            BaslangicTarihi = new DateTime(2024, 2, 9, 23, 5, 21, 721, DateTimeKind.Local).AddTicks(9549),
>>>>>>>> origin/asd:DietApp/DietApp.DAL/Migrations/20240209200521_a.Designer.cs
                            BitisTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Boy = 170.0,
                            Cinsiyet = false,
                            GunlukKalori = 3000.0,
                            HedefKilo = 70.0,
                            HedefSuMiktari = 2000.0,
                            Isim = "ahmet",
                            Kilo = 80.0,
                            KullaniciGirisID = 3,
                            Soyisim = "mehmet",
                            Yas = 18
                        },
                        new
                        {
                            ID = 4,
<<<<<<<< HEAD:DietApp/DietApp.DAL/Migrations/20240209195155_initial.Designer.cs
                            BaslangicTarihi = new DateTime(2024, 2, 9, 22, 51, 54, 727, DateTimeKind.Local).AddTicks(7306),
========
                            BaslangicTarihi = new DateTime(2024, 2, 9, 23, 5, 21, 721, DateTimeKind.Local).AddTicks(9550),
>>>>>>>> origin/asd:DietApp/DietApp.DAL/Migrations/20240209200521_a.Designer.cs
                            BitisTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Boy = 170.0,
                            Cinsiyet = false,
                            GunlukKalori = 3000.0,
                            HedefKilo = 70.0,
                            HedefSuMiktari = 2000.0,
                            Isim = "ahmet",
                            Kilo = 80.0,
                            KullaniciGirisID = 4,
                            Soyisim = "mehmet",
                            Yas = 18
                        },
                        new
                        {
                            ID = 5,
<<<<<<<< HEAD:DietApp/DietApp.DAL/Migrations/20240209195155_initial.Designer.cs
                            BaslangicTarihi = new DateTime(2024, 2, 9, 22, 51, 54, 727, DateTimeKind.Local).AddTicks(7308),
========
                            BaslangicTarihi = new DateTime(2024, 2, 9, 23, 5, 21, 721, DateTimeKind.Local).AddTicks(9551),
>>>>>>>> origin/asd:DietApp/DietApp.DAL/Migrations/20240209200521_a.Designer.cs
                            BitisTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Boy = 170.0,
                            Cinsiyet = false,
                            GunlukKalori = 3000.0,
                            HedefKilo = 70.0,
                            HedefSuMiktari = 2000.0,
                            Isim = "admin",
                            Kilo = 80.0,
                            KullaniciGirisID = 5,
                            Soyisim = "adminoğlu",
                            Yas = 18
                        });
                });

            modelBuilder.Entity("DietApp.Entities.Ogun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("GunlukRaporID")
                        .HasColumnType("int");

                    b.Property<double>("Kalori")
                        .HasColumnType("float");

                    b.Property<double>("KarbonhidratMiktari")
                        .HasColumnType("float");

                    b.Property<int>("KullaniciKisiselID")
                        .HasColumnType("int");

                    b.Property<int>("OgunAdi")
                        .HasColumnType("int");

                    b.Property<double>("ProteinMiktari")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<double>("YagMiktari")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("GunlukRaporID");

                    b.HasIndex("KullaniciKisiselID");

                    b.ToTable("Ogun");
                });

            modelBuilder.Entity("DietApp.Entities.Su", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("KullaniciKisiselId")
                        .HasColumnType("int");

                    b.Property<double>("SuMiktari")
                        .HasColumnType("float");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciKisiselId");

                    b.ToTable("Su");
                });

            modelBuilder.Entity("DietApp.Entities.Yemek", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("FotografYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kalori")
                        .HasColumnType("float");

                    b.Property<double>("KarbonhidratMiktari")
                        .HasColumnType("float");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.Property<double>("ProteinMiktari")
                        .HasColumnType("float");

                    b.Property<double>("YagMiktari")
                        .HasColumnType("float");

                    b.Property<string>("YemekAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KategoriID");

                    b.ToTable("Yemek");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FotografYolu = "Fotograflar\\Elma.jpg",
                            Kalori = 95.0,
                            KarbonhidratMiktari = 19.0,
                            KategoriID = 1,
                            ProteinMiktari = 0.29999999999999999,
                            YagMiktari = 0.29999999999999999,
                            YemekAdi = "Elma"
                        });
                });

            modelBuilder.Entity("DietApp.Entities.YemekMiktari", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<double>("Kalori")
                        .HasColumnType("float");

                    b.Property<double>("KarbonhidratMiktari")
                        .HasColumnType("float");

                    b.Property<double>("MiktarGr")
                        .HasColumnType("float");

                    b.Property<double>("ProteinMiktari")
                        .HasColumnType("float");

                    b.Property<double>("YagMiktari")
                        .HasColumnType("float");

                    b.Property<int>("YemekID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("YemekID");

                    b.ToTable("YemekMiktari");
                });

            modelBuilder.Entity("DietApp.Entities.YemekMiktarOgun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("OgunID")
                        .HasColumnType("int");

                    b.Property<int>("YemekMiktarID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OgunID");

                    b.HasIndex("YemekMiktarID");

                    b.ToTable("YemekMiktarOgun");
                });

            modelBuilder.Entity("DietApp.Entities.GunlukRapor", b =>
                {
                    b.HasOne("DietApp.Entities.KullaniciKisisel", null)
                        .WithMany("KullanicininRaporlari")
                        .HasForeignKey("KullaniciKisiselID");
                });

            modelBuilder.Entity("DietApp.Entities.KullaniciKisisel", b =>
                {
                    b.HasOne("DietApp.Entities.KullaniciGiris", "KullaniciGiris")
                        .WithOne("KullaniciKisisel")
                        .HasForeignKey("DietApp.Entities.KullaniciKisisel", "KullaniciGirisID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KullaniciGiris");
                });

            modelBuilder.Entity("DietApp.Entities.Ogun", b =>
                {
                    b.HasOne("DietApp.Entities.GunlukRapor", null)
                        .WithMany("GunlukRaporunOgunListesi")
                        .HasForeignKey("GunlukRaporID");

                    b.HasOne("DietApp.Entities.KullaniciKisisel", "KullaniciKisisel")
                        .WithMany("KullanicininOgunleri")
                        .HasForeignKey("KullaniciKisiselID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KullaniciKisisel");
                });

            modelBuilder.Entity("DietApp.Entities.Su", b =>
                {
                    b.HasOne("DietApp.Entities.KullaniciKisisel", "KullaniciKisisel")
                        .WithMany("IcilenSu")
                        .HasForeignKey("KullaniciKisiselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KullaniciKisisel");
                });

            modelBuilder.Entity("DietApp.Entities.Yemek", b =>
                {
                    b.HasOne("DietApp.Entities.Kategori", "Kategori")
                        .WithMany("KategorininYemekListesi")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("DietApp.Entities.YemekMiktari", b =>
                {
                    b.HasOne("DietApp.Entities.Yemek", "YenilenYemek")
                        .WithMany("YemekMiktarlari")
                        .HasForeignKey("YemekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YenilenYemek");
                });

            modelBuilder.Entity("DietApp.Entities.YemekMiktarOgun", b =>
                {
                    b.HasOne("DietApp.Entities.Ogun", "Ogun")
                        .WithMany("OgununYemekleri")
                        .HasForeignKey("OgunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietApp.Entities.YemekMiktari", "Yemek")
                        .WithMany("YemeginOgunleri")
                        .HasForeignKey("YemekMiktarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogun");

                    b.Navigation("Yemek");
                });

            modelBuilder.Entity("DietApp.Entities.GunlukRapor", b =>
                {
                    b.Navigation("GunlukRaporunOgunListesi");
                });

            modelBuilder.Entity("DietApp.Entities.Kategori", b =>
                {
                    b.Navigation("KategorininYemekListesi");
                });

            modelBuilder.Entity("DietApp.Entities.KullaniciGiris", b =>
                {
                    b.Navigation("KullaniciKisisel")
                        .IsRequired();
                });

            modelBuilder.Entity("DietApp.Entities.KullaniciKisisel", b =>
                {
                    b.Navigation("IcilenSu");

                    b.Navigation("KullanicininOgunleri");

                    b.Navigation("KullanicininRaporlari");
                });

            modelBuilder.Entity("DietApp.Entities.Ogun", b =>
                {
                    b.Navigation("OgununYemekleri");
                });

            modelBuilder.Entity("DietApp.Entities.Yemek", b =>
                {
                    b.Navigation("YemekMiktarlari");
                });

            modelBuilder.Entity("DietApp.Entities.YemekMiktari", b =>
                {
                    b.Navigation("YemeginOgunleri");
                });
#pragma warning restore 612, 618
        }
    }
}
